[package]
name = "barley-std"
version = "0.1.0"
edition = "2021"

[dependencies]
barley-runtime = { version = "0.3.0", path = "../barley-runtime" }
futures = "0.3.28"
tokio = { version = "1.28.2", features = ["time"] }
