[package]
name = "cargo-barley"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.0", features = ["derive"] }

[workspace]
members = [
  "barley-runtime",
  "barley-utils",
  "barley-proc",
  "barley-interface",
  "examples"
]
