[package]
name = "barley-utils"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait = "0.1.68"
barley-runtime = { path = "../barley-runtime" }
tokio = { version = "1.28.1", optional = true }

[features]
default = ["time"]
time = ["dep:tokio", "tokio?/time"]

[dev-dependencies]
tokio = { version = "1.28.1", features = ["test-util", "macros"] }
