[package]
name = "barley-apt"
version = "0.1.0"
edition = "2021"

[dependencies.barley-runtime]
version = "0.6.1"
path = "../../barley-runtime"
features = ["next"]

[dependencies]
async-trait = "0.1.71"
tokio = { version = "1.29.1", features = ["process"] }
