[package]
name = "barley-proc"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.57"
quote = "1.0.27"
syn = { version = "2.0.16", features = ["full"] }
